apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-edca-integration-helm.name" . }}-iam-client-secret
  labels:
  {{- include "eric-edca-integration-helm.kubernetes-io-info" .| nindent 4 }}
  annotations:
{{- include "eric-edca-integration-helm.helm-annotations" .| nindent 4 }}
type: Opaque
data:
  clientSecret: {{ .Values.global.clientSecret | default (derivePassword 1 "long" .Release.Name .Chart.Name .Values.global.hosts.iam | b64enc) | quote }}
