{{- if eq (include "eric-edca-integration-helm.osmn" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-edca-integration-helm.name" . }}-object-storage-mn-secret
  labels:
  {{- include "eric-edca-integration-helm.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-edca-integration-helm.helm-annotations" .| nindent 4 }}
type: Opaque
data:
  accesskey: {{ template "eric-edca-integration-helm.objectstoreAccesskey" }}
  secretkey: {{ template "eric-edca-integration-helm.objectstoreSecretkey" }}
{{- end -}}
