apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: drg-simulator
  name: drg-simulator
spec:
  containers:
  - image: armdocker.rnd.ericsson.se/proj-edca-dev/drg-image:1.0.5
    name: drg-simulator
    command:
    - sh
    - -c
    - --
    args:
    - while true;do sleep 30;done
    resources: {}
    volumeMounts:
    - name: drg
      mountPath: "/app/configuration"
  volumes:
  - name: drg
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}