zapConfig:
  baseUrl: "http://edca-integration-vulnerability-analysis.hahn205.rnd.gic.ericsson.se/catalog"
  scanType: "api"
  config_dir: "zap/config"
  globalConfig:
    - id: "100000"
      action: "IGNORE"
      message: "A Server Error response code was returned by the server"
    - id: "100001"
      action: "IGNORE"
      message: "Unexpected Content-Type was returned"
  endpoints:
  - name: "EDCA_BulkData"
    url: "/v1/bulk-data-repository"
    config:
    - id: "10021"
      action: "IGNORE"
      message: "X-Content-Type-Options Header Missing"
    - id: "100001"
      action: "IGNORE"
      message: "Unexpected Content-Type was returned"
    - id: "10036"
      action: "IGNORE"
      message: "Server Leaks Version Information via Server HTTP Response Header Field"
  - name: "EDCA_Dataspace"
    url: "/v1/data-space"
    config:
    - id: "10021"
      action: "IGNORE"
      message: "X-Content-Type-Options Header Missing"
    - id: "100001"
      action: "IGNORE"
      message: "Unexpected Content-Type was returned"
    - id: "10036"
      action: "IGNORE"
      message: "Server Leaks Version Information via Server HTTP Response Header Field"
  - name: "EDCA_MessageBus"
    url: "/v1/message-bus"
    config:
    - id: "10021"
      action: "IGNORE"
      message: "X-Content-Type-Options Header Missing"
    - id: "100001"
      action: "IGNORE"
      message: "Unexpected Content-Type was returned"
    - id: "10036"
      action: "IGNORE"
      message: "Server Leaks Version Information via Server HTTP Response Header Field"
  - name: "EDCA_Notification"
    url: "/v1/notification-topic"
    config:
    - id: "10021"
      action: "IGNORE"
      message: "X-Content-Type-Options Header Missing"
    - id: "100001"
      action: "IGNORE"
      message: "Unexpected Content-Type was returned"
    - id: "10036"
      action: "IGNORE"
      message: "Server Leaks Version Information via Server HTTP Response Header Field"
  - name: "EDCA_Catalog"
    url: "/v1/metadata"
    config:
    - id: "10021"
      action: "IGNORE"
      message: "X-Content-Type-Options Header Missing"
    - id: "100000"
      action: "IGNORE"
      message: "A Server Error response code was returned by the server"
    - id: "100001"
      action: "IGNORE"
      message: "Unexpected Content-Type was returned"
    - id: "10036"
      action: "IGNORE"
      message: "Server Leaks Version Information via Server HTTP Response Header Field"
    - id: "90022"
      action: "IGNORE"
      message: "Application Error Disclosure"
  - name: "EDCA_DMaap_post"
    url: "/topics/create"
    config:
    - id: "10021"
      action: "IGNORE"
      message: "X-Content-Type-Options Header Missing"
    - id: "100000"
      action: "IGNORE"
      message: "A Server Error response code was returned by the server"
    - id: "100001"
      action: "IGNORE"
      message: "Unexpected Content-Type was returned"
    - id: "10036"
      action: "IGNORE"
      message: "Server Leaks Version Information via Server HTTP Response Header Field"
    - id: "90022"
      action: "IGNORE"
      message: "Application Error Disclosure"
  - name: "EDCA_DMaap_get"
    url: "/topics"
    config:
    - id: "10021"
      action: "IGNORE"
      message: "X-Content-Type-Options Header Missing"
    - id: "100000"
      action: "IGNORE"
      message: "A Server Error response code was returned by the server"
    - id: "100001"
      action: "IGNORE"
      message: "Unexpected Content-Type was returned"
    - id: "10036"
      action: "IGNORE"
      message: "Server Leaks Version Information via Server HTTP Response Header Field"
    - id: "90022"
      action: "IGNORE"
      message: "Application Error Disclosure"
  - name: "EDCA_DMaap_get_topic"
    url: "/topics/pm-data"
    config:
    - id: "10021"
      action: "IGNORE"
      message: "X-Content-Type-Options Header Missing"
    - id: "100000"
      action: "IGNORE"
      message: "A Server Error response code was returned by the server"
    - id: "100001"
      action: "IGNORE"
      message: "Unexpected Content-Type was returned"
    - id: "10036"
      action: "IGNORE"
      message: "Server Leaks Version Information via Server HTTP Response Header Field"
    - id: "90022"
      action: "IGNORE"
      message: "Application Error Disclosure"
  report:
    dir: "zap/reports"
    format:
    - html
    - md
  properties:
    zap_container_port: 4040